from datetime import datetime
import os

class TypesetterAgent:
    def __init__(self, output_dir="data/library"):
        self.output_dir = output_dir
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def generate_delta_update(self, book_title, existing_path, new_content):
        """
        Appends a 'Research Addendum' instead of overwriting.
        Simulates "PDF" export by creating/updating a Markdown file.
        """
        addendum = f"\n\n## --- RESEARCH ADDENDUM: {datetime.now().strftime('%Y-%m-%d %H:%M')} ---\n"
        addendum += new_content
        
        # In a real app we might parse PDF, append page, save.
        # Here we deal with a persistent text/md file acting as the book source.
        file_path = existing_path if existing_path else os.path.join(self.output_dir, f"{book_title.replace(' ', '_')}.md")
        
        mode = 'a' if os.path.exists(file_path) else 'w'
        with open(file_path, mode) as f:
            if mode == 'w':
                f.write(f"# {book_title}\n\nGenerated by AI #6 Publishing House\n")
            f.write(addendum)
            
        return file_path

    def create_brief(self, master_doc_content, title):
        """
        Generates the 10-page 'Executive Brief' for friends.
        """
        # Truncate or Summarize Mock
        brief_content = f"# EXECUTIVE BRIEF: {title}\n\n"
        brief_content += f"**Social/Mobile Optimized Summary**\n\n"
        brief_content += master_doc_content[:1000] + "\n\n...(Full details in Master Volume)..."
        
        path = os.path.join(self.output_dir, f"BRIEF_{title.replace(' ', '_')}.md")
        with open(path, 'w') as f:
            f.write(brief_content)
            
        return path
