import json
import os
import importlib.util
import sys
from typing import List, Dict

class IngestionAgent:
    def __init__(self, strategy_folder: str):
        self.folder = strategy_folder

    def load_strategies(self) -> List[Dict]:
        """
        Loads raw strategy data.
        In a full implementation, this would parse the Python strategy files 
        and extract their configuration/logic.
        
        For this prototype, we use the structured JSON representations 
        that would be generated by the 'Syntax Validator' step.
        """
        # MOCK DATA from Prompt (Arjo Strategies)
        # This represents the JSON output the LLM would generate from the Video/Code
        arjo_strategies = [
            {
                "id": "ARJO_MMC_EP1",
                "name": "PD_Array_Directional_Bias",
                "layer_4_logic": {
                    "Context": "Price is moving towards a PD Array.",
                    "Trigger": "Price reacts from a Discount Array.",
                    "Entry": "Target nearest Premium Array.",
                    "Stop": "Below the Discount Array."
                },
                 "environment_filters": {
                    "Bias": "Bullish if reacting from Discount."
                }
            },
            {
                "id": "ARJO_MMC_EP2",
                "name": "Market_Structure_FVA",
                "layer_4_logic": {
                    "Context": "Bearish Trend (Lower ITHs).",
                    "Trigger": "Price breaks ITL creating Bearish FVA.",
                    "Entry": "Retracement into Bearish FVA (ITH-ITL range).",
                    "Stop": "Above ITH (Protection)."
                },
                "environment_filters": {
                    "Structure": "Must clear ITL."
                }
            },
             {
                "id": "ARJO_MMC_EP3",
                "name": "Order_Flow_Leg",
                "layer_4_logic": {
                   "Context": "Valid Order Flow Leg (Swing + FVG).",
                   "Trigger": "Retracement into the FVG of the Leg.",
                   "Entry": "Limit at FVG.",
                   "Stop": "Beyond Swing Point (LLOD)."
                },
                 "environment_filters": {
                    "Intention": "Leg must have FVG."
                }
            },
            {
                "id": "ARJO_MMC_EP6",
                "name": "FVG_Created_At_Resistance",
                "layer_4_logic": {
                    "Context": "Price hits Unmitigated Opposing Array.",
                    "Trigger": "Reaction creates new FVG in trend direction.",
                    "Entry": "Limit at new FVG.",
                    "Stop": "Behind FVG/Swing."
                },
                "environment_filters": {
                    "Quality": "Must be created immediately at resistance."
                }
            },
             {
                "id": "ARJO_MMC_EP6_DUPE", # For Deduplication Test
                "name": "Resistance_Reaction_FVG",
                "layer_4_logic": {
                     "Context": "Price hits Unmitigated Opposing Array.",
                    "Trigger": "Reaction creates new FVG in trend direction.",
                    "Entry": "Limit at new FVG.",
                    "Stop": "Behind FVG/Swing."
                },
                "environment_filters": {}
            }
        ]
        
        return arjo_strategies
